### ISSUE TITLE
Fix edit-address form fields

### ISSUE THREAD

**Issue by AmirHosseinKarimi** [MahdiY/Persian-woocommerce-shipping#6]
Hi, In the my-account page > edit-address endpoint, we have city field, but it just shown city ID. We need use select field here too, like as checkout page.
According to #5 the code base if not up-to-date. If you update it, I can look at it and try to add this feature.
Thanks.

**Comment by farazacademy0** [comment]
Dear Mahdi

Greetings
I appreciate your kind email and I'm really happy to hear from you asking
for help. I promise to do my best and I will do whatever you ask me with
such a great passion for this field of developing and programming that
believe me I never felt a love for anything more than this new hubby. But
honestly I'm a dummy in programming and I just discovered github around 10
days ago 😄 because I was forced to make a website for the company that I
work for... And this is also the first time that I am making a web page 😊
but frankly I found web and app development soooooo fun and lovely that I
want to change my job to be a developer! So please forgive me for
disappointing you brother but I promise to learn fast and be a good student
for you 😉 just give me some time to look into this subject and after
understanding what's going on in here I will help you soooooo much more
than you expected me to 🙏☺️
BTW, my name is Farhad it's soooo great to meet you, I hope to see u in
person cuz I think we can do a lot of things together!
I will text or call u later
Bests
Farhad

**Comment by MahdiY** [comment]
Salaam @AmirHosseinKarimi 
This feature is available in the premium version.
https://nabik.net/product/persian-woocommerce-shipping-pro/
